import os
import json
import hmac
import hashlib
from datetime import datetime, timezone
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak

class ForensicReportGenerator:
    """Generates comprehensive PDF forensic reports."""

    def __init__(self):
        self.styles = getSampleStyleSheet()
        # Default font is Helvetica as per ReportLab defaults, but ensure we don't need external fonts.

        self.title_style = ParagraphStyle(
            'TitleStyle',
            parent=self.styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=24,
            alignment=TA_CENTER,
            spaceAfter=20
        )
        self.header_style = ParagraphStyle(
            'HeaderStyle',
            parent=self.styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=16,
            spaceBefore=15,
            spaceAfter=10
        )
        self.sub_header_style = ParagraphStyle(
            'SubHeaderStyle',
            parent=self.styles['Heading3'],
            fontName='Helvetica-Bold',
            fontSize=14,
            spaceBefore=10,
            spaceAfter=5
        )
        self.normal_style = ParagraphStyle(
            'NormalStyle',
            parent=self.styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            spaceBefore=5,
            spaceAfter=5
        )

    def _create_header_footer(self, canvas, doc, case_id):
        """Draws header on each page."""
        canvas.saveState()
        canvas.setFont('Helvetica', 9)
        # Left
        canvas.drawString(36, letter[1] - 30, f"Case ID: {case_id}")
        # Center
        canvas.drawCentredString(letter[0] / 2.0, letter[1] - 30, "MOFFIT v0.1 — CONFIDENTIAL")
        # Right
        canvas.drawRightString(letter[0] - 36, letter[1] - 30, f"Page {doc.page}")
        canvas.restoreState()

    def generate(self, case: dict, findings: list[dict], timeline_map: dict, custody: dict, narrative: str, output_path: str) -> None:
        """Generates the PDF report and saves it to output_path."""
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=54,
            bottomMargin=36
        )

        story = []

        # 1. COVER PAGE
        story.append(Spacer(1, 100))
        story.append(Paragraph("DIGITAL FORENSIC INVESTIGATION REPORT", self.title_style))
        story.append(Spacer(1, 50))

        cover_details = [
            f"Case Name: {case.get('name', 'N/A')}",
            f"Case ID: {case.get('id', 'N/A')}",
            f"Investigator: {case.get('investigator', 'N/A')}",
            f"Date Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"Status: {case.get('status', 'N/A')}"
        ]

        for detail in cover_details:
            story.append(Paragraph(detail, self.normal_style))

        story.append(Spacer(1, 100))
        story.append(Paragraph("Generated by MOFFIT v0.1", ParagraphStyle('Centered', parent=self.normal_style, alignment=TA_CENTER)))
        story.append(Paragraph("CONFIDENTIAL — FOR OFFICIAL USE ONLY", ParagraphStyle('CenteredBold', parent=self.normal_style, fontName='Helvetica-Bold', alignment=TA_CENTER)))

        story.append(PageBreak())

        # 2. EXECUTIVE SUMMARY
        story.append(Paragraph("2. EXECUTIVE SUMMARY", self.header_style))
        story.append(Paragraph(narrative if narrative else "No narrative provided.", self.normal_style))
        story.append(Spacer(1, 20))

        # 3. SCOPE AND METHODOLOGY
        story.append(Paragraph("3. SCOPE AND METHODOLOGY", self.header_style))
        methodology_text = (
            "This investigation was conducted using MOFFIT v0.1. Data was sourced from the PaySim dataset "
            "(Lopez-Rojas et al., 2016). Analytical methods employed include graph analysis and pattern detection "
            "to identify anomalous and potentially fraudulent behavior within mobile money transactions. "
            "All processes maintain cryptographic integrity to ensure forensic soundness."
        )
        story.append(Paragraph(methodology_text, self.normal_style))
        story.append(Spacer(1, 20))

        # 4. EVIDENCE INTEGRITY TABLE
        story.append(Paragraph("4. EVIDENCE INTEGRITY TABLE", self.header_style))
        evidence_data = [["Item", "Filename", "SHA-256 (trunc)", "Acquired At"]]
        for idx, item in enumerate(custody.get('items', [])):
            item_type = item.get('type', f"Item {idx+1}")
            filename = item.get('filename', item.get('label', 'N/A'))
            sha256 = item.get('sha256', '')
            sha256_trunc = sha256[:16] + "..." if len(sha256) > 16 else sha256
            acquired = item.get('acquired_at', 'N/A')
            evidence_data.append([item_type, filename, sha256_trunc, acquired])

        t_evidence = Table(evidence_data, colWidths=[60, 200, 150, 120])
        t_evidence.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1EFE8')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.black)
        ]))
        story.append(t_evidence)
        story.append(Spacer(1, 20))

        # 5. FINDINGS TABLE
        # Cap at 100, sorted by severity then confidence
        # Severity mapping for sorting
        sev_map = {"high": 3, "medium": 2, "low": 1}

        def finding_sort_key(f):
            sev_val = sev_map.get(f.get('severity', 'low').lower(), 0)
            conf_val = f.get('confidence', 0.0)
            return (sev_val, conf_val)

        sorted_findings = sorted(findings, key=finding_sort_key, reverse=True)
        top_findings = sorted_findings[:100]

        story.append(Paragraph(f"5. FINDINGS TABLE (Top {len(top_findings)} of {len(findings)} total)", self.header_style))
        findings_data = [["Severity", "Pattern", "Account ID", "Steps", "Confidence", "Description"]]

        findings_style = [
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1EFE8')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
            ('VALIGN', (0, 0), (-1, -1), 'TOP')
        ]

        for i, f in enumerate(top_findings):
            row_idx = i + 1
            severity = f.get('severity', 'Low').capitalize()
            # Background coloring for severity
            if severity.lower() == 'high':
                findings_style.append(('BACKGROUND', (0, row_idx), (0, row_idx), colors.HexColor('#FCEBEB')))
            elif severity.lower() == 'medium':
                findings_style.append(('BACKGROUND', (0, row_idx), (0, row_idx), colors.HexColor('#FAEEDA')))
            elif severity.lower() == 'low':
                findings_style.append(('BACKGROUND', (0, row_idx), (0, row_idx), colors.HexColor('#EAF3DE')))

            pattern = f.get('finding_type', f.get('pattern', 'N/A'))

            # Extract account ID
            accounts = f.get('account_ids', [])
            if isinstance(accounts, list) and len(accounts) > 0:
                acc_id = accounts[0]
            elif isinstance(accounts, str):
                acc_id = accounts
            elif 'account_id' in f:
                acc_id = f['account_id']
            else:
                acc_id = 'N/A'

            steps = f"{f.get('step_start', '')}-{f.get('step_end', '')}"
            confidence = f"{f.get('confidence', 0.0) * 100:.0f}%"
            desc = Paragraph(f.get('description', ''), ParagraphStyle('desc', fontName='Helvetica', fontSize=8))

            findings_data.append([severity, pattern, acc_id, steps, confidence, desc])

        t_findings = Table(findings_data, colWidths=[50, 70, 70, 50, 60, 240])
        t_findings.setStyle(TableStyle(findings_style))
        story.append(t_findings)
        story.append(Spacer(1, 20))

        # 6. ACCOUNT TIMELINES
        story.append(Paragraph("6. ACCOUNT TIMELINES", self.header_style))
        for account_id, events in timeline_map.items():
            story.append(Paragraph(f"Timeline for Account: {account_id}", self.sub_header_style))

            tl_data = [["Step", "Event Type", "Amount (KES)", "Bal Before", "Bal After", "Annotation"]]
            for event in events:
                tl_data.append([
                    str(event.get('step', '')),
                    str(event.get('event_type', '')),
                    f"{event.get('amount', 0.0):.2f}",
                    f"{event.get('balance_before', 0.0):.2f}",
                    f"{event.get('balance_after', 0.0):.2f}",
                    Paragraph(event.get('annotation', ''), ParagraphStyle('ann', fontName='Helvetica', fontSize=8))
                ])

            t_tl = Table(tl_data, colWidths=[40, 90, 80, 80, 80, 170])
            t_tl.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1EFE8')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
                ('VALIGN', (0, 0), (-1, -1), 'TOP')
            ]))
            story.append(t_tl)
            story.append(Spacer(1, 15))

        story.append(PageBreak())

        # 7. APPENDIX A: Chain of custody
        story.append(Paragraph("7. APPENDIX A: Chain of Custody", self.header_style))

        custody_data = [["Key", "Value"]]

        def add_dict_to_custody_data(d, prefix=""):
            for k, v in d.items():
                if isinstance(v, list):
                    custody_data.append([Paragraph(prefix + str(k), self.normal_style), "List of items:"])
                    for i, item in enumerate(v):
                        if isinstance(item, dict):
                            add_dict_to_custody_data(item, prefix + f"  Item {i+1} - ")
                        else:
                            custody_data.append([Paragraph(prefix + f"  Item {i+1}", self.normal_style), Paragraph(str(item), self.normal_style)])
                elif isinstance(v, dict):
                    custody_data.append([Paragraph(prefix + str(k), self.normal_style), "Dictionary:"])
                    add_dict_to_custody_data(v, prefix + "  ")
                else:
                    custody_data.append([Paragraph(prefix + str(k), self.normal_style), Paragraph(str(v), self.normal_style)])

        add_dict_to_custody_data(custody)

        t_custody = Table(custody_data, colWidths=[150, 390])
        t_custody.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1EFE8')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
            ('VALIGN', (0, 0), (-1, -1), 'TOP')
        ]))
        story.append(t_custody)
        story.append(Spacer(1, 20))

        # 8. APPENDIX B: Integrity signature
        story.append(Paragraph("8. APPENDIX B: Integrity Signature", self.header_style))

        # Generate an HMAC signature of the case info + custody items
        signature_data = json.dumps({
            "case_id": case.get('id', ''),
            "custody_hash": custody.get('manifest_hash', ''),
            "generated_at": datetime.now(timezone.utc).isoformat()
        }, sort_keys=True).encode()

        secret_key = b"MOFFIT_FORENSIC_KEY"
        signature = hmac.new(secret_key, signature_data, hashlib.sha256).hexdigest()

        story.append(Paragraph(f"<b>HMAC-SHA256 Signature:</b> {signature}", self.normal_style))
        verification_text = (
            "Verification Instructions: This signature guarantees the integrity of the PDF report contents "
            "as generated by MOFFIT. Any modifications to the report or the underlying custody manifest will "
            "result in a mismatch during cryptographic verification. "
            "To verify, compute the HMAC-SHA256 of the case ID, custody manifest hash, and timestamp using "
            "the MOFFIT forensic verification utility."
        )
        story.append(Paragraph(verification_text, self.normal_style))

        # Build document
        doc.build(story, onFirstPage=lambda c, d: self._create_header_footer(c, d, case.get('id', 'N/A')),
                  onLaterPages=lambda c, d: self._create_header_footer(c, d, case.get('id', 'N/A')))
